=== Jdaniel1/G0P9OJXML/G0P9OJ_0924/G0P9OJ_kurzusfelvetel.dtd
<!ELEMENT G0P9OJ_kurzusfelvetel (hallgato,kurzusok)>
    <!ATTLIST G0P9OJ_kurzusfelvetel tanev CDATA #REQUIRED>
    <!ATTLIST G0P9OJ_kurzusfelvetel egyetem CDATA #REQUIRED>
<!ELEMENT hallgato (hnev,szulev,szak)>
<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
    <!ATTLIST szak evf NMTOKEN #REQUIRED>
<!ELEMENT kurzusok (kurzus*)>
<!ELEMENT kurzus (kurzusnev,kredit,hely,idopont+,oktato?,oraado?)>
    <!ATTLIST kurzus id ID #REQUIRED>
    <!ATTLIST kurzus jovahagyas (igen | nem) "nem">
    <!ATTLIST kurzus nyelv CDATA #IMPLIED>
<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>

=== Jdaniel1/G0P9OJXML/G0P9OJ_0924/G0P9OJ_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE G0P9OJ_kurzusfelvetel SYSTEM "G0P9OJ_kurzusfelvetel.dtd">

<G0P9OJ_kurzusfelvetel tanev="2024/25/1" egyetem="Miskolci Egyetem">
    <hallgato>
        <hnev>Jobbágy Dániel<hnev/>
        <szulev>2001<szulev/>
        <szak evf="5">Mérnökinformatikus</szak>
    </hallgato>
    <kurzusok>
        <kurzus id="GEIAL331-B" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Webtech1</kurzusnev>
            <kredit>5</kredit>
            <hely>EA1</hely>
            <idopont>Hétfő 10-12</idopont>
            <oktato>Agárdi Anita</oktato>
        </kurzus>
        <kurzus id="GEIAL32B-B" jovahagyas="nem" nyelv="magyar">
            <kurzusnev>Oracle</kurzusnev>
            <kredit>5</kredit>
            <hely>Info/103</hely>
            <idopont>Hétfő 8-10</idopont>
            <oktato>Kovács László</oktato>
            <oraado>Szűcs Miklós</oraado>
        </kurzus>
        <kurzus id="GEIAL31G-B" jovahagyas="nem">
            <kurzusnev>Korszerű Tech.</kurzusnev>
            <kredit>5</kredit>
            <hely>Info/103</hely>
            <idopont>Hétfő 12-14</idopont>
            <oktato>Árvai László</oktato>
            <oraado>Soós Róbert</oraado>
        </kurzus>
        <kurzus id="GEIAL336-B" jovahagyas="igen">
            <kurzusnev>Webalk C#</kurzusnev>
            <kredit>5</kredit>
            <hely>Info/101</hely>
            <idopont>Kedd 14-18</idopont>
            <oktato>Árvai László</oktato>
        </kurzus>    
    </kurzusok>
</G0P9OJ_kurzusfelvetel>

=== Jdaniel1/G0P9OJXML/G0P9OJ_1015/G0P9OJ_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE G0P9OJ_kurzusfelvetel SYSTEM "G0P9OJ_kurzusfelvetel.dtd">

<G0P9OJ_kurzusfelvetel tanev="2024/2025" egyetem="ME" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kurzusfelvetel1.xsd">

    <hallgato id="G0P9OJ.ME">
        <nev>Jobbágy Dániel</nev>
        <szulev>2001.01.24.</szulev>
        <szak evf="5">Mérnökinformatikus Bsc</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL332-B">
            <kurzusnev>Adatkezelés XML környezetben</kurzusnev>
            <kredit>5</kredit>
            <hely>I103.</hely>
            <idopont>Kedd 10:00-13:30</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>

        <kurzus id="GEIAL332-B">
            <kurzusnev>Adatkezelés XML környezetben</kurzusnev>
            <kredit>5</kredit>
            <hely>I103.</hely>
            <idopont>Kedd 10:00-13:30</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>

        <kurzus id="GEIAL32B-B" nyelv="magyar">
            <kurzusnev>Oracle Rendszergazda</kurzusnev>
            <kredit>5</kredit>
            <hely>I103.</hely>
            <idopont>Hétfő 08:00-09:30</idopont>
            <oktato>Dr. Kovács László</oktato>
            <oraado>Szűcs Miklós</oraado>
        </kurzus>

        <kurzus id="GEIAL335-B" nyelv="magyar">
            <kurzusnev>Mobil programozási alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>I103.</hely>
            <idopont>Hétfő 16:00-19:30</idopont>
            <oktato>Dr. Agárdi Antia</oktato>
        </kurzus>
    </kurzusok>

</G0P9OJ_kurzusfelvetel>
