=== Jdaniel1/G0P9OJXML/XMLTaskG0P9OJ/DOMParseG0P9OJ/XMLSchemaG0P9OJ.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">


    <xs:element name="tulajID" type="tulajIDTipus"/>
    <xs:element name="motorID" type="motorIDTipus"/>
    <xs:element name="jarmuID" type="jarmuID"/>
    <xs:element name="gyartasID" type="gyartoIDTipus"/>
    <xs:element name="biztosit" type="xs:string"/>

    <xs:element name="vnev" type="xs:string"/>
    <xs:element name="knev" type="xs:string"/>

    <xs:element name="meghajtas" type="meghajtasTipus"/>
    <xs:element name="loero" type="xs:string"/>
    <xs:element name="nyomatek" type="xs:string"/>

    <xs:element name="felulet" type="feluletTipus"/>
    <xs:element name="engedely" type="engedelyTipus"/>
    <xs:element name="szin" type="xs:string"/>

    <xs:element name="marka" type="xs:string"/>
    <xs:element name="modell" type="xs:string"/>
    <xs:element name="evszam" type="xs:gYear"/>

    <xs:element name="idopont" type="xs:date"/>


    <xs:simpleType name="rendszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z]-[A-Z][A-Z]-[0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tulajIDTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="motorIDTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{14}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="meghajtasTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="benzin|dizel|hibrid|elektromos"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="jarmuID">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{17}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="feluletTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="matt|reszleges|teljes"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="engedelyTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="van|nincs"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="gyartoIDTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][A-Z]"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="gepjarmuType">
        <xs:sequence>
            <xs:element name="munkagep" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="tulajID" />
                        <xs:element ref="motorID"/>
                        <xs:element ref="jarmuID"/>
                        <xs:element ref="gyartasID" />
                        <xs:element ref="biztosit" minOccurs="0"/>
                    </xs:sequence>
                    <xs:attribute name="rendszam" type="rendszamTipus" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="tulajdonos" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev">
                         <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="vnev" />
                                <xs:element ref="knev" />
                            </xs:sequence>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="jogositvany_szama" type="tulajIDTipus" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="motor" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="meghajtas" />
                        <xs:element ref="loero" />
                        <xs:element ref="nyomatek" />
                    </xs:sequence>
                    <xs:attribute name="motorszam" type="motorIDTipus" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="karosszeria" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="felulet" />
                        <xs:element ref="engedely" />
                        <xs:element ref="szin" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="alvazszam" type="jarmuID" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="gyartas" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="marka" />
                        <xs:element ref="modell" />
                        <xs:element ref="evszam" />
                    </xs:sequence>
                    <xs:attribute name="gyartasID" type="gyartoIDTipus" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="birtoklas" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="birtoklas_kezdete"/>
                    </xs:sequence>
                        <xs:attribute name="rendszam" type="rendszamTipus" use="required"/>
                        <xs:attribute name="jogositvany_szama" type="tulajIDTipus" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="gepjarmu" type="gepjarmuType"/>



    <xs:key name="munkagep_kulcs">
        <xs:selector xpath="munkagep" />
        <xs:field xpath="@rendszam" />
    </xs:key>

    <xs:key name="tulajdonos_kulcs">
        <xs:selector xpath="tulajdonos" />
        <xs:field xpath="@jogositvany_szama" />
    </xs:key>

    <xs:key name="motor_kulcs">
        <xs:selector xpath="motor" />
        <xs:field xpath="@motorszam" />
    </xs:key>

    <xs:key name="karosszeria_kulcs">
        <xs:selector xpath="karosszeria" />
        <xs:field xpath="@alvazszam" />
    </xs:key>

    <xs:key name="gyartas_kulcs">
        <xs:selector xpath="gyartas" />
        <xs:field xpath="@gyartasID" />
    </xs:key>



    <xs:keyref refer="tulajdonos_kulcs" name="tulaj_idegen_kulcs">
        <xs:selector xpath="munkagep" />
        <xs:field xpath="tulajID" />
    </xs:keyref>

    <xs:keyref refer="motor_kulcs" name="motor_idegen_kulcs">
        <xs:selector xpath="munkagep" />
        <xs:field xpath="motorID" />
    </xs:keyref>

    <xs:keyref refer="karosszeria_kulcs" name="karosszeria_idegen_kulcs">
        <xs:selector xpath="munkagep" />
        <xs:field xpath="jarmuID" />
    </xs:keyref>

    <xs:keyref refer="gyartas_kulcs" name="gyartas_idegen_kulcs">
        <xs:selector xpath="munkagep" />
        <xs:field xpath="gyartasID" />
    </xs:keyref>

    <xs:keyref refer="munkagep_kulcs" name="birtoklas_idegen_kulcs"/>
        <xs:selector xpath="birtoklas" />
        <xs:field xpath="@rendszam" />
        <xs:field xpath="@jogositvany_szama" />
    </xs:keyref>



    <xs:unique name="uniqueTartalmazas">
        <xs:selector xpath="karosszeria"/>
        <xs:field xpath="@alvazszam"/>
    </xs:unique>

</xs:schema>

=== Jdaniel1/G0P9OJXML/XMLTaskG0P9OJ/DOMParseG0P9OJ/src/XMLG0P9OJModify.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gepjarmu xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaG0P9OJ.xsd">

    <!-- munkagepek -->

    <munkagep rendszam="AB-CD-123">
        <tulajID>HU345678</tulajID>
        <motorID>100FDSAF008F1G</motorID>
        <jarmuID>0FSFDSFFF70000019</jarmuID>
        <gyartasID>15B</gyartasID>
        <biztosit>FSDAG34</biztosit>
    </munkagep>

    <munkagep rendszam="MM-AB-123">
        <tulajID>HU346544</tulajID>
        <motorID>100FDFGDS58F1G</motorID>
        <jarmuID>0FSFDSCCC70000019</jarmuID>
        <gyartasID>10B</gyartasID>
        <biztosit>HSDAG34</biztosit>
    </munkagep>

    <munkagep rendszam="KD-QS-510">
        <tulajID>RO378544</tulajID>
        <motorID>540FDFGDS58F1G</motorID>
        <jarmuID>3HSFDSCCC70000019</jarmuID>
        <gyartasID>98C</gyartasID>
    </munkagep>

    <!-- tulajdonosok -->

    <tulajdonos jogositvany_szama="FR346544">
        <nev>
            <vnev>Kovacs</vnev>
            <knev>Arpad</knev>
        </nev>
    </tulajdonos>

    <tulajdonos jogositvany_szama="HU346544">
        <nev>
            <vnev>Szabo</vnev>
            <knev>Peter</knev>
        </nev>
    </tulajdonos>

    <tulajdonos jogositvany_szama="RO378544">
        <nev>
            <vnev>Elekes</vnev>
            <knev>Tibor</knev>
        </nev>
    </tulajdonos>

    <!-- motorok -->

    <motor motorszam="100FDSAF008F1G">
        <meghajtas>dizel</meghajtas>
        <loero>68</loero>
        <nyomatek>160 Nm</nyomatek>
    </motor>

    <motor motorszam="100FDFGDS58F1G">
        <meghajtas>hibrid</meghajtas>
        <loero>75</loero>
        <nyomatek>107 Nm</nyomatek>
    </motor>

    <motor motorszam="540FDFGDS58F1G">
        <meghajtas>elektromos</meghajtas>
        <loero>150</loero>
        <nyomatek>310 Nm</nyomatek>
    </motor>

    <!-- karosszériák -->

    <karosszeria alvazszam="0FSFDSFFF70000019">
        <felulet>matt</felulet>
        <engedely>van</engedely>
        <szin>feher</szin>
        <szin>szürke</szin>
    </karosszeria>

    <karosszeria alvazszam="0FSFDSCCC70000019">
        <felulet>teljes</felulet>
        <engedely>van</engedely>
        <szin>feher</szin>
    </karosszeria>

    <karosszeria alvazszam="3HSFDSCCC70000019">
        <felulet>reszleges</felulet>
        <engedely>van</engedely>
        <szin>zöld</szin>
        <szin>fekete</szin>
        <szin>szürke</szin>
    </karosszeria>

    <!-- informaciok -->

    <gyartas gyartasID="15B">
        <marka>Hyundai</marka>
        <modell>R25Z-9AK</modell>
        <evjarat>2020</evjarat>
    </gyartas>

    <gyartas gyartasID="10B">
        <marka>JCB</marka>
        <modell>1CX</modell>
        <evjarat>2008</evjarat>
    </gyartas>

    <gyartas gyartasID="98C">
        <marka>JCB</marka>
        <modell>4CX</modell>
        <evjarat>2019</evjarat>
    </gyartas>

    <!-- birtoklas kapcsolatok -->

    <birtoklas jogositvany_szama="HU345678" rendszam="AB-CD-123">
        <birtoklas_kezdete>2022-01-01</birtoklas_kezdete>
    </birtoklas>

    <birtoklas jogositvany_szama="HU346544" rendszam="AA-BB-720">
        <birtoklas_kezdete>2021-11-04</birtoklas_kezdete>
    </birtoklas>

    <birtoklas jogositvany_szama="RO378544" rendszam="KD-QS-510">
        <birtoklas_kezdete>2020-05-18</birtoklas_kezdete>
    </birtoklas>

</gepjarmu>

=== Jdaniel1/G0P9OJXML/XMLTaskG0P9OJ/DOMParseG0P9OJ/src/XMLG0P9OJ1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gepjarmu xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaG0P9OJ.xsd">
    <munkagep rendszam="AB-CD-123">
        <tulajID>HU345678</tulajID>
        <motorID>100FDSAF008F1G</motorID>
        <jarmuID>0FSFDSFFF70000019</jarmuID>
        <gyartasID>15B</gyartasID>
        <biztosit>FSDAG34</biztosit>
    </munkagep>

    <munkagep rendszam="AA-BB-720">
        <tulajID>HU346544</tulajID>
        <motorID>100FDFGDS58F1G</motorID>
        <jarmuID>0FSFDSCCC70000019</jarmuID>
        <gyartasID>10B</gyartasID>
        <biztosit>HSDAG34</biztosit>
    </munkagep>

    <munkagep rendszam="KD-QS-510">
        <tulajID>RO378544</tulajID>
        <motorID>540FDFGDS58F1G</motorID>
        <jarmuID>3HSFDSCCC70000019</jarmuID>
        <gyartasID>98C</gyartasID>
    </munkagep>

    <tulajdonos jogositvany_szama="HU345678">
        <nev>
            <vnev>Kovacs</vnev>
            <knev>Arpad</knev>
        </nev>
    </tulajdonos>

    <tulajdonos jogositvany_szama="HU346544">
        <nev>
            <vnev>Szabo</vnev>
            <knev>Peter</knev>
        </nev>
    </tulajdonos>

    <tulajdonos jogositvany_szama="RO378544">
        <nev>
            <vnev>Elekes</vnev>
            <knev>Tibor</knev>
        </nev>
    </tulajdonos>

    <motor motorszam="100FDSAF008F1G">
        <meghajtas>dizel</meghajtas>
        <loero>68</loero>
        <nyomatek>160 Nm</nyomatek>
    </motor>

    <motor motorszam="100FDFGDS58F1G">
        <meghajtas>benzin</meghajtas>
        <loero>75</loero>
        <nyomatek>107 Nm</nyomatek>
    </motor>

    <motor motorszam="540FDFGDS58F1G">
        <meghajtas>elektromos</meghajtas>
        <loero>150</loero>
        <nyomatek>310 Nm</nyomatek>
    </motor>

    <karosszeria alvazszam="0FSFDSFFF70000019">
        <felulet>matt</felulet>
        <engedely>nincs</engedely>
        <szin>feher</szin>
        <szin>szurke</szin>
    </karosszeria>

    <karosszeria alvazszam="0FSFDSCCC70000019">
        <felulet>teljes</felulet>
        <engedely>van</engedely>
        <szin>feher</szin>
        <szin/>
    </karosszeria>

    <karosszeria alvazszam="3HSFDSCCC70000019">
        <felulet>reszleges</felulet>
        <engedely>nincs</engedely>
        <szin>zold</szin>
        <szin>fekete</szin>
        <szin>szurke</szin>
    </karosszeria>

    <gyartas gyartasID="15B">
        <marka>Hyundai</marka>
        <modell>R25Z-9AK</modell>
        <evszam>2004</evszam>
    </gyartas>

    <gyartas gyartasID="10B">
        <marka>JCB</marka>
        <modell>1CX</modell>
        <evszam>2011</evszam>
    </gyartas>

    <gyartas gyartasID="98C">
        <marka>JCB</marka>
        <modell>4CX</modell>
        <evszam>2021</evszam>
    </gyartas>

    <birtoklas jogositvany_szama="HU345678" rendszam="AB-CD-123">
        <birtoklas_kezdete>2023-01-01</birtoklas_kezdete>
    </birtoklas>

    <birtoklas jogositvany_szama="HU346544" rendszam="AA-BB-720">
        <birtoklas_kezdete>2022-11-04</birtoklas_kezdete>
    </birtoklas>

    <birtoklas jogositvany_szama="RO378544" rendszam="KD-QS-510">
        <birtoklas_kezdete>2021-05-18</birtoklas_kezdete>
    </birtoklas>
</gepjarmu>
